// Generates Framer Motion variants as a ready-to-paste React module.
// Output is TypeScript-compatible JSX.

export function formatFramer(motionSpec) {
  const { animations, tokens, meta } = motionSpec;

  const lines = [];
  lines.push(`// Framer Motion Variants — ${meta.url}`);
  lines.push(`// Generated by motionlang — ${meta.timestamp}`);
  lines.push(`// ${animations.length} animations detected\n`);
  lines.push(`import { motion, useReducedMotion } from 'framer-motion';\n`);

  // Token constants
  lines.push(`// ── Motion Tokens ─────────────────────────────────────────────`);
  lines.push(`export const motionTokens = {`);
  lines.push(`  durations: {`);
  for (const d of tokens.durations) {
    const key = d.bucket || 'md';
    lines.push(`    ${key}: ${parseInt(d.value) / 1000}, // ${d.value}`);
  }
  lines.push(`  },`);
  lines.push(`  easings: {`);
  for (const e of tokens.easings) {
    const key = e.humanName.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    lines.push(`    ${key}: '${e.value}',`);
  }
  lines.push(`  },`);
  lines.push(`};\n`);

  // Variants per animation
  lines.push(`// ── Animation Variants ────────────────────────────────────────`);
  for (const anim of animations) {
    const variantName = toCamelCase(anim.id);
    const durationSec = anim.duration ? (anim.duration / 1000).toFixed(2) : '0.4';
    const ease = anim.easing || 'easeOut';

    lines.push(`\nexport const ${variantName}Variants = {`);
    lines.push(`  hidden: ${buildFramerHidden(anim)},`);
    lines.push(`  visible: {`);
    lines.push(`    opacity: 1,`);
    if (anim.pattern === 'slide-up') lines.push(`    y: 0,`);
    if (anim.pattern === 'morph') lines.push(`    scaleX: 1,`);
    lines.push(`    transition: {`);
    lines.push(`      duration: ${durationSec},`);
    lines.push(`      ease: '${ease}',`);
    if (anim.delay) lines.push(`      delay: ${(anim.delay / 1000).toFixed(2)},`);
    lines.push(`    },`);
    lines.push(`  },`);
    lines.push(`};\n`);
  }

  // Reduced motion hook
  lines.push(`// ── Reduced Motion Hook ───────────────────────────────────────`);
  lines.push(`export function useMotionVariants(variants) {`);
  lines.push(`  const shouldReduce = useReducedMotion();`);
  lines.push(`  if (shouldReduce) {`);
  lines.push(`    return {`);
  lines.push(`      hidden: { opacity: 0 },`);
  lines.push(`      visible: { opacity: 1, transition: { duration: 0.01 } },`);
  lines.push(`    };`);
  lines.push(`  }`);
  lines.push(`  return variants;`);
  lines.push(`}`);

  // Usage example
  lines.push(`\n// ── Usage Example ─────────────────────────────────────────────`);
  if (animations.length > 0) {
    const first = toCamelCase(animations[0].id);
    lines.push(`// import { ${first}Variants, useMotionVariants } from './motion-variants';`);
    lines.push(`//`);
    lines.push(`// function MyComponent() {`);
    lines.push(`//   const variants = useMotionVariants(${first}Variants);`);
    lines.push(`//   return (`);
    lines.push(`//     <motion.div`);
    lines.push(`//       variants={variants}`);
    lines.push(`//       initial="hidden"`);
    lines.push(`//       whileInView="visible"`);
    lines.push(`//       viewport={{ once: true, amount: 0.2 }}`);
    lines.push(`//     />`);
    lines.push(`//   );`);
    lines.push(`// }`);
  }

  return lines.join('\n');
}

function buildFramerHidden(anim) {
  if (anim.pattern === 'slide-up') return '{ opacity: 0, y: 40 }';
  if (anim.pattern === 'morph')    return '{ opacity: 1, scaleX: 0 }';
  return '{ opacity: 0 }';
}

function toCamelCase(str) {
  return str.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}