// Generates a pure CSS implementation using transitions +
// IntersectionObserver class toggling. No JS library required.

export function formatCss(motionSpec) {
  const { animations, tokens, meta } = motionSpec;

  const lines = [];
  lines.push(`/* CSS Motion Spec — ${meta.url} */`);
  if (meta.component) {
    lines.push(`/* Component: ${meta.component.label} (${meta.component.selector}) */`);
  }
  lines.push(`/* Generated by motionlang — ${meta.timestamp} */`);
  lines.push(`/* ${animations.length} animations detected */\n`);

  // CSS custom properties (tokens)
  lines.push(`/* ── Motion Tokens ─────────────────────────────────────────── */`);
  lines.push(`:root {`);
  for (const d of tokens.durations) {
    lines.push(`  --${d.name}: ${d.value};`);
  }
  for (const e of tokens.easings) {
    lines.push(`  --${e.name}: ${e.value};`);
  }
  lines.push(`}\n`);

  // Reduced motion override
  lines.push(`/* ── Reduced Motion ─────────────────────────────────────────── */`);
  lines.push(`@media (prefers-reduced-motion: reduce) {`);
  lines.push(`  *, *::before, *::after {`);
  lines.push(`    animation-duration: 0.01ms !important;`);
  lines.push(`    animation-iteration-count: 1 !important;`);
  lines.push(`    transition-duration: 0.01ms !important;`);
  lines.push(`  }`);
  lines.push(`}\n`);

  // Per-animation classes
  lines.push(`/* ── Animation Classes ──────────────────────────────────────── */`);
  for (const anim of animations) {
    const cls = anim.id;
    const duration = anim.duration ? `${anim.duration}ms` : 'var(--duration-sm)';
    const ease = anim.easing || 'ease-out';
    const delay = anim.delay ? `${anim.delay}ms` : '0ms';

    lines.push(`\n/* ${anim.id} — ${anim.pattern} */`);
    lines.push(`.${cls} {`);

    // Hidden state
    if (anim.pattern === 'fade-in' || anim.pattern === 'slide-up') {
      lines.push(`  opacity: 0;`);
    }
    if (anim.pattern === 'slide-up') {
      lines.push(`  transform: translateY(40px);`);
    }
    if (anim.pattern === 'morph') {
      lines.push(`  transform: scaleX(0);`);
      lines.push(`  transform-origin: left;`);
    }

    lines.push(`  transition: all ${duration} ${ease} ${delay};`);
    lines.push(`}\n`);

    // Visible state (triggered by .is-visible class via IntersectionObserver)
    lines.push(`.${cls}.is-visible {`);
    lines.push(`  opacity: 1;`);
    if (anim.pattern === 'slide-up') lines.push(`  transform: translateY(0);`);
    if (anim.pattern === 'morph')    lines.push(`  transform: scaleX(1);`);
    lines.push(`}`);
  }

  // IntersectionObserver JS snippet
  lines.push(`\n\n/* ── IntersectionObserver Setup (paste into your JS) ────────── */`);
  lines.push(`/*`);
  lines.push(`const observer = new IntersectionObserver((entries) => {`);
  lines.push(`  entries.forEach(entry => {`);
  lines.push(`    if (entry.isIntersecting) {`);
  lines.push(`      entry.target.classList.add('is-visible');`);
  lines.push(`    }`);
  lines.push(`  });`);
  lines.push(`}, { threshold: 0.15 });\n`);
  lines.push(`document.querySelectorAll('[class*="anim-"]').forEach(el => observer.observe(el));`);
  lines.push(`*/`);

  return lines.join('\n');
}