// Generates ready-to-paste GSAP ScrollTrigger code from the motion spec.
// Output is a self-contained JS module — import and drop into any project.

export function formatGsap(motionSpec) {
  const { animations, tokens, meta } = motionSpec;

  const lines = [];
  lines.push(`// GSAP Motion Spec — ${meta.url}`);
  lines.push(`// Generated by motionlang — ${meta.timestamp}`);
  if (meta.component) {
    lines.push(`// Component: ${meta.component.label} (${meta.component.selector})`);
  }
  lines.push(`// ${animations.length} animations detected\n`);
  lines.push(`import gsap from 'gsap';`);
  lines.push(`import { ScrollTrigger } from 'gsap/ScrollTrigger';`);
  lines.push(`gsap.registerPlugin(ScrollTrigger);\n`);

  // Motion tokens as constants
  lines.push(`// ── Motion Tokens ─────────────────────────────────────────────`);
  for (const d of tokens.durations) {
    const varName = d.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    lines.push(`const ${varName} = ${parseInt(d.value) / 1000}; // ${d.value}`);
  }
  for (const e of tokens.easings) {
    const varName = e.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    lines.push(`const ${varName} = '${e.value}'; // ${e.humanName}`);
  }
  lines.push('');

  // One GSAP block per animation
  lines.push(`// ── Animations ────────────────────────────────────────────────`);
  for (const anim of animations) {
    lines.push(`\n// ${anim.id} — ${anim.pattern}`);
    if (anim.element) {
     lines.push(`// Element: ${String(anim.element?.outerHtml || anim.element?.classes || anim.element || '').substring(0, 80)}`);
    }

    const gsapProps = buildGsapProps(anim);
    const durationSec = anim.duration ? (anim.duration / 1000).toFixed(2) : '0.4';
    const ease = anim.easing ? `'${anim.easing}'` : `'power2.out'`;

    if (anim.pattern === 'scroll-scrub' || anim.pattern === 'pin-section') {
      lines.push(`gsap.to('[data-anim="${anim.id}"]', {`);
      lines.push(`  ${gsapProps},`);
      lines.push(`  duration: ${durationSec},`);
      lines.push(`  ease: ${ease},`);
      lines.push(`  scrollTrigger: {`);
      lines.push(`    trigger: '[data-anim="${anim.id}"]',`);
      lines.push(`    start: 'top 80%',`);
      lines.push(`    end: 'bottom 20%',`);
      lines.push(`    scrub: ${anim.pattern === 'scroll-scrub' ? 'true' : 'false'},`);
      lines.push(`    pin: ${anim.pattern === 'pin-section' ? 'true' : 'false'},`);
      lines.push(`  },`);
      lines.push(`});`);
    } else {
      lines.push(`gsap.from('[data-anim="${anim.id}"]', {`);
      lines.push(`  ${gsapProps},`);
      lines.push(`  duration: ${durationSec},`);
      lines.push(`  ease: ${ease},`);
      if (anim.delay) lines.push(`  delay: ${(anim.delay / 1000).toFixed(2)},`);
      lines.push(`  scrollTrigger: {`);
      lines.push(`    trigger: '[data-anim="${anim.id}"]',`);
      lines.push(`    start: 'top 85%',`);
      lines.push(`    toggleActions: 'play none none reverse',`);
      lines.push(`  },`);
      lines.push(`});`);
    }
  }

  // Reduced motion wrapper
  lines.push(`\n// ── Reduced Motion ────────────────────────────────────────────`);
  lines.push(`if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {`);
  lines.push(`  gsap.globalTimeline.timeScale(0); // pause all animations`);
  lines.push(`}`);

  return lines.join('\n');
}

function buildGsapProps(anim) {
  const props = [];
  if (anim.pattern === 'fade-in' || anim.pattern === 'slide-up') props.push('opacity: 0');
  if (anim.pattern === 'slide-up') props.push('y: 40');
  if (anim.pattern === 'morph') props.push('scaleX: 0');
  if (anim.pattern === 'state-change') props.push('opacity: 0.8');
  if (props.length === 0) props.push('opacity: 0');
  return props.join(', ');
}